### ISSUE TITLE
[FEATURE]  News feed calendar etcetera 

### ISSUE THREAD

**Issue by baloe1541** [mennovanhout/flutter-hdashboards-issues#37] opened 2023-09-18 15:15 UTC
I like to see more widgets like a news feed in my Home Screen weather forecast from buienradar calendar and more to customize

**Comment by mennovanhout** [comment] 2023-09-18 16:40
Buienradar is already possible with a virtual camera.
But I get that these features are wanted. For now i close it as it is a duplicate of

#32

**Closed by mennovanhout** 2023-09-18 16:40 UTC
Labels: enhancement
