### ISSUE TITLE
[BUG] Tado thermostate has no controls

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#36] opened 2023-09-17 10:21 UTC
**To Reproduce**
- Add a Tado thermostaat or rediator button using Tadozones app in your homey.
- Add a device for this Thermostate in hdashboard and use as label Target temperature (ingestelde temperatuur)
- Save the dashboard

**Expected behavior**
To have a device which I can set the temperature between the limit of 5 to 25 degrees and have a list of possible scheme settings when I do a long push.

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/113d7927-c9c0-4fb7-8730-f2003ace18c4)

Tado devices:
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/837d50c7-c2d8-406b-9cd7-50e81da3c92f)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/f16c2597-16a1-46b7-a6e1-b1ff5a3fa1f3)

**Using information (please complete the following information):**
 - OS: all
 - Browser All

**Homey device**
 - Device: HP23
 - tadoZones 5.1.7 test app.

**Comment by mennovanhout** [comment] 2023-09-18 13:48
Duplicate of #10

**Closed by mennovanhout** 2023-09-18 13:48 UTC
Labels: bug
